### PR TITLE
Fix up rmw_dds_common documentation when using rosdoc2

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. This patch:

- Updates the `rmw_dds_common`'s Doxyfile.
- Cleans up `rmw_dds_common` API doc blocks.
- Rearranges a few `md` files to avoid path issues.

### CODE REVIEW

**Comment by hidmic** [comment]
FYI the links to header files in FEATURES.md are not picked up by Doxygen and so they are broken. To the best of my knowledge, only docs.ros.org links to generated documentation, once we have them online, are the only ones that will work in both generated documentation and Github rendered documents.

**Comment by hidmic** [comment]
Ci up to `rmw_dds_common`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15227/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9947/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12907/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15410/)

**Comment by hidmic** [comment]
Alright, CI's green. Going in !

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2021-9-16/22372/1

**Pull request merged**
