### PR TITLE
Fix potential memory leak

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
Just a minor fix. (Not to open an issue)

Signed-off-by: Chen.Lihui <lihui.chen@sony.com>

### CODE REVIEW

**Comment by iuhilnehc-ynos** [comment]
I wonder if `rcutils_string_array_fini(enclaves);` needs to be called at external even if the return value is NOT RMW_RET_OK. If so(why the behavior is different from node or namespace?), I'll close this PR.

**Comment by iuhilnehc-ynos** [comment]
@ivanpauno 

Could you please help me review this?

**Review by clalancette — APPROVED** [review]
Seems reasonable to me to cleanup on error.  I'll run CI on it next.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12244/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7221/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9963/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12137/)

**Review by ivanpauno — APPROVED** [review]
Thanks for the fix

**Pull request merged**
