### PR TITLE
Add fault injection macro unit tests (#27)

### PR DESCRIPTION
**Pull request by ahcorde**
* Add fault injection macro unit tests

Signed-off-by: Stephen Brawner <brawner@gmail.com>

* target definitions

Signed-off-by: Stephen Brawner <brawner@gmail.com>

* PR Fixup

Signed-off-by: Stephen Brawner <brawner@gmail.com>

### CODE REVIEW

**Comment by brawner** [comment]
Is this backport missing a PR? The fault injection test fails in the Fpr job

**Comment by ahcorde** [comment]
@ros-pull-request-builder retest this please

**Comment by ahcorde** [comment]
Compiling `up-to` `rmw_dds_common` and tested `rmw_dds_common`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12731/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7692/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10445/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12678/)

**Comment by ahcorde** [comment]
@brawner CI is green!

**Review by brawner — APPROVED** [review]

**Pull request merged**
